# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Lint
      run: |
        poetry run isort --check .
        poetry run black --check .
    - name: Ensure tag and version match
      run: |
        echo "v$(poetry version --short)" | grep -Eq "^${GITHUB_REF_NAME}\$" || exit 1
        echo "artifact=palette-$(poetry version --short).zip" >> $GITHUB_ENV
    - name: Package
      run: |
        poetry run poe package
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: Auto generated release
        draft: true
        prerelease: false
    - name: Upload to Release
      uses: csexton/release-asset-action@v3
      with:
        file: ${{ env.artifact }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        release-url: ${{ steps.create_release.outputs.upload_url }}
